### ISSUE TITLE
issues with vitrtualenv/condaenv

### ISSUE THREAD

**Issue by toastyghosty13** [slopp/myhybrid#1]
HI!! your project has helped a lot since I am trying to publish an Rshiny app that uses python code. I am trying to source a python file in the app, but am having so much trouble with creating a virtual environment that will be used by rshiny. I have tried to create a virtual environment with shell, create a conda environment with shell, create both virtual and conda envs as the first steps of the rshiny app, and even tried reply_python(). I was wondering how you were able to set up your virtual environment, since I tried to follow the steps [here](https://www.dabapps.com/blog/introduction-to-pip-and-virtualenv-python/), but have had no success. Did you do something different in order to create and then use the virtual environment in the app? so far I have gotten closest with 
`reticulate::py_install(envname='py_env_FF', method = 'auto', packages=c('sklearn', 'pandas', 'numpy','joblib', 'requests', 'geopy'), pip = TRUE, python_version = 'python3')`

but have had no such luck. Is there also a specific way you told the shiny app to use the virtual env or conda env? I also keep having issues with shinyapps.io only using python 2.7, and cannot figure out a way to specify what version of python for shinyapps.io to use when deploying the app. Sorry if this is a lot. Thanks in advanced!!!!

**Comment by slopp** [comment]
I am glad you found this example helpful! I'd recommend posting your question to community.rstudio.com. 

In my example, I was using Rstudio Connect which knows how to restore Python and R environments. based on the `RETICULATE_PYTHON` environment variable. I don't think this is possible today with shinyapps.io, which was only designed to manage R environments.

**Comment by toastyghosty13** [comment]
rip, well thank you for your fast response! at least now I know :)
